% Purpose: Creates and displays difficulty selection window with easy, medium, and hard options
% Parameters: None
% Return values: None

function getDifficulty() 
    % Create a uifigure for the difficulty selection window with a blue background
    bg = uifigure(Name="Choose Difficulty", ...
        NumberTitle="off", ...
        Color=[0.50 0.65 0.80], ...
        Position=[600 400 400 250],Resize="off",ToolBar="none");
    % Create a button group to ensures only one can be selected
    % source: https://au.mathworks.com/help/matlab/ref/uibuttongroup.html#bu7pj9g-5
    menu = uibuttongroup(bg,Position=[140 110 120 90]);
    
    % Add difficulty options to the button group with tags
    easyButton = uitogglebutton(menu,Text="Easy", ...
        Position=[10 56 100 22],Tag="easy");
    
    mediumButton = uitogglebutton(menu,Text="Medium", ...
        Position= [10 32 100 22],Tag="medium");
    
    hardButton = uitogglebutton(menu,Text="Hard", ...
        Position=[10 8 100 22],Tag="hard");
    
    % Create a Start Game button that launches the game with the selected difficulty
    % source: https://au.mathworks.com/help/matlab/ref/uibutton.html
    startBtn = uibutton(bg, ...
        Text="Start Game", ...
        FontWeight="bold", ...
        Position=[150 40 100 30], ...
        ButtonPushedFcn=@(src,event) startGame(menu,bg),BackgroundColor=[0.6 0.8 0.6]);
end