% Purpose: Displays an instructions window at game start or mid-game.
% Parameters: isFirstTime – boolean value indicating whether this is the start of game (true) or opened from the game window (false).
% Return values: None

function showInstructions(isFirstTime)
    
    % Create a new figure window with specified size, title, and background color
    instructionWindow = figure(Name="How to Play", ...
        NumberTitle="off", ...
        Position=[600 400 400 300], ...
        Color=[0.9 0.95 1],ToolBar="none",Resize="off");
    
    % Add main heading at the top of the instruction window
    uicontrol(Style="text", ...
        Parent=instructionWindow, ...
        String="How to Play Minesweeper", ...
        FontSize=16, FontWeight="bold", ...
        HorizontalAlignment="center", ...
        BackgroundColor=[0.9 0.95 1], ...
        Position=[20 240 360 40])
    
    % Add instruction text explaining how to play Minesweeper
    uicontrol(Style="text", ...
        Parent=instructionWindow, ...
        String={ ...
        sprintf("Left-click a square to reveal it\n" + ...
        "If you reveal a mine you lose!\n" + ...
        "Numbers in revealed cells show how many mines are in adjacent cells\n" + ...
        "Right-click a cell to flag it as a mine\n" + ...
        "To win reveal all safe cells!\n\n" + ...
        "Good luck !!") ...
        }, ...
        Position=[20 40 360 190], ...
        FontSize=14, ...
        HorizontalAlignment="center", ...
        BackgroundColor=[0.9 0.95 1])

    % Check if the window is being shown for the first time (at game start)
    if isFirstTime
        % Create Start Game button which opens the difficulty selection window
        uicontrol(Style="pushbutton", ...
            Parent=instructionWindow, ...
            String="Start Game", ...
            Position=[150 20 100 40], ...
            FontSize=12, ...
            Callback=@(~,~) openDifficultyWindow(instructionWindow));
    else
        % If not the first time, show a "Back to Game" button
        % This button closes the instructions and return to the game
        uicontrol(Style="pushbutton", ...
            Parent=instructionWindow, ...
            String="Back to Game", ...
            Position=[150 20 100 40], ...
            FontSize=12, ...
            Callback=@(~,~) close(instructionWindow))
    end
end